import Head from "next/head";
import Image from "next/image";
import React from "react";

export default function Header() {
  return (
    // <Head>
    //   <title>
    //     <Image src="./fwef.png" alt="dev" /> Match-on
    //   </title>
    // </Head>
    <Head>
      <title>Match-On</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/fwef.png" />
    </Head>
  );
}
